### ISSUE TITLE
`EnforceSignatures` cop doesn't detect `sig(:final)`

### ISSUE THREAD

**Issue by jacobobq** [Shopify/rubocop-sorbet#134]
It appears that the `EnforceSignatures` cop has trouble accepting `sig(:final)` as a valid signature. This might also affect other signature-based cops.

Here's a failing code example.
```ruby
# typed: true

class Boundary
  sig(:final) { returns(Elem) }
  def call
    trace { filter }
  end
end
```

Here's the cop configuration:
```yml
Sorbet/EnforceSignatures:
  Enabled: true
  AutoCorrect: false
  Severity: warning
  Exclude:
    - 'config/**/*'
   ...
```

![imagen](https://user-images.githubusercontent.com/69577078/216617521-cad81f41-0e04-4c37-9408-440b370c6f4d.png)

#### Expected behaviour:

The method doesn't trigger the cop's warning, since it has a valid signature.
