### ISSUE TITLE
Inconsistent rubocop-sorbet Cop Status Between Documentation and rubocop --show-cops Output

### ISSUE THREAD

**Issue by jacksonmiras** [Shopify/rubocop-sorbet#317]
#### Description  

The [rubocop-sorbet documentation](https://github.com/Shopify/rubocop-sorbet/blob/main/manual/cops_sorbet.md) states that certain cops, such as `Sorbet/AllowIncompatibleOverride`, are **enabled by default** (`Enabled by default: Enabled`). However, when executing `rubocop --show-cops`, all cops appear as **disabled** (`Enabled: false`).  

#### Reproduction Steps  
Running the following command produces an unexpected result:  

```bash
$ rubocop --show-cops

# Available cops (966) + config for my-project:
# Department 'Sorbet' (42):
Sorbet/AllowIncompatibleOverride:
  Description: 'Disallows using `.override(allow_incompatible: true)`.'
  Enabled: false
  VersionAdded: 0.2.0
...
```

#### Expected Behavior  
The cops listed in the documentation as enabled by default should appear as enabled when running `rubocop --show-cops`.  

#### Actual Behavior  
All cops in the `Sorbet` department are marked as disabled, contradicting the documentation.  

#### Configuration  
Below is the current `.rubocop.yml` configuration:  

```yaml
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.3.5
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/migrate/**/*.rb
    - db/queue_migrate/**/*.rb
    - lib/**/*.rb
    - spec/**/*.rb
    - sorbet/rbi/shims/**/*.rbi
  Exclude:
    - bin/**/*
    - crm_schema.rb
    - db/cache_schema.rb
    - db/cable_schema.rb
    - db/cable_schema.rb
    - db/schema.rb
    - node_modules/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
```

#### Question  
Is this a known issue with `rubocop-sorbet`, or could there be a misconfiguration in my setup?
